name: $pluginName
main: $pluginMain
depend: [ Kotlin, WorldEdit ]
api-version: '1.16'
version: $version
commands:
  region:
    usage: /<command>
  area:
    usage: /<command>

permissions:
  regions.*:
    default: op
    children:
      regions.command: true
      regions.action: true
  regions.command:
    default: op
  regions.action:
    default: op