name: $pluginName
main: $pluginMain
depend: [Kotlin, Tap, WorldEdit]
api-version: '1.13'
version: $pluginVersion
commands:
  region:
    usage: /<command> help
permissions:
  regions.*:
    default: op
    children:
      regions.command: true
      regions.action: true
  regions.command:
    default: op
  regions.action:
    default: op